### ISSUE TITLE
bell 102 tone 1200/2200   why 2400?

### ISSUE THREAD

**Issue by Jeeprock** [handiko/Arduino-APRS#5]
Hi, in simple aprs with arduino why do you use 2400 hz tone ?  
It's supposed to be 2200 hz no ?

**Comment by handiko** [comment]
Hello, i use 2400 Hz tone because the way i construct the AFSK
modulation, which is using delaymicrosecond() function. I am using
delaymicrosecond() to construct 1200Hz square wave. if i use 2200Hz, the
baudrate would not synchronous easily with the 1200Hz. therefore, i use
2400Hz because it is integer multiple of 1200Hz so it will keep the 1200
signal baudrate. furthermore, 2400Hz tone would easily demodulated by the
existing APRS decoder (tested using direwolf and real world on-air
testing).
thanks


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by strud** [comment]
Hi @handiko 
I have made use of your nice code base to implement a c++ class and it is mostly working well.

However, I think due to the 2400Hz tone frequency, many decoders are having trouble with it.

DireWolf works well, but this is probably one of if not the best decoder out there. 

Are you saying that to implement 2200Hz we would need to go with a sinusoid?

Thanks

**Comment by handiko** [comment]
> Hi @handiko
> I have made use of your nice code base to implement a c++ class and it is mostly working well.
> 
> However, I think due to the 2400Hz tone frequency, many decoders are having trouble with it.
> 
> DireWolf works well, but this is probably one of if not the best decoder out there.
> 
> Are you saying that to implement 2200Hz we would need to go with a sinusoid?
> 
> Thanks

Sorry for the very late response. :(

It should be fine. Actually, I already built this kind of APRS modulator/tracker using a simple microcontroller with 1200/2400Hz tone since 2012, and always works and decodable without any problem, even at a very low signal level.

In the past (2012-ish) the receiving station was using AGWPE, Alinco DR-135mk2 TNC/digipeater board, Argent Data Systems digipeater board, and even using more modern GQRX-SDR built-in decoder works well.

**Comment by mzakiab** [comment]
audio nya ada di speaker, tapi di bila TX, DireWolf tidak bisa decode. kenapa yer?
